name: my_notes
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 0.16.1
  cloud_firestore: 0.13.4
  provider: 4.3.1
  intl: ^0.16.1
  flutter_svg: ^0.19.3
  molten_navigationbar_flutter: ^0.0.1
  font_awesome_flutter: ^8.11.0
  avatar_glow: ^1.2.0
  cached_network_image: ^2.5.0
  image_picker: ^0.6.7+22
  firebase_storage: 3.0.3
  flutter_slidable: ^0.5.7
  share: ^2.0.0
  expansion_card: ^0.1.0
  another_flushbar: ^1.10.13
  rflutter_alert: ^1.1.0
  sliding_sheet: ^0.4.1
  introduction_screen: ^2.0.0
  shared_preferences:
  after_layout: ^1.0.7+2
  flutter_spinkit: ^5.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BalooBhai
      fonts:
        - asset: assets/fonts/BalooBhai-Regular.ttf
          #style: SemiBold
    - family: Baloo Bhai 2
      fonts:
        - asset: assets/fonts/BalooBhai2.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
